apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sahhhall/auth
          env:
            - name: PORT
              value: "3000"
            - name: KAFKA_CLIENT_ID
              value: "auth-service"
            - name: KAFKA_BROKERS
              value: kafka-srv:9092
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: GRPC_SERVER
              value: "user-srv:50051"
            - name: REDIS_URL
              value: "redis://redis-srv:6379"
            - name: FRONT_END_BASE_URL
              value: "http://client-srv:5173"  
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_PASS
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_REFRESH_SECRET
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
