apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: sahhhall/client
          env:
            - name: VITE_BASE_URL
              value: "http://roadmappro.site" 
            - name: VITE_NOTIFICATION_URL
              value: "http://roadmappro.site/notification"
            - name: VITE_BOOKING_URL
              value: "http://roadmappro.site/mentor" 
            - name: VITE_GOOGLE_CLIENT
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: VITE_GOOGLE_CLIENT          
            - name: VITE_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_PUBLISHABLE_KEY
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173