apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: sahhhall/notification
          env:
            - name: PORT
              value: "3006"
            - name: KAFKA_CLIENT_ID
              value: "http://notification-service"
            - name: KAFKA_BROKERS
              value: kafka-srv:9092
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_PASS
            - name: FRONT_END_BASE_URL
              value: "http://client-srv:5173"      
          ports:
            - containerPort: 3006
---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
