apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db-depl
  template:
    metadata:
      labels:
        app: payment-db-depl
    spec:
      containers:
        - name: payment-db-depl
          image: postgres:13
          envFrom:
            - configMapRef:
                name: postgres-config

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
spec:
  selector:
    app: payment-db-depl
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
