apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: sahhhall/payment 
          env:
            - name: PORT
              value: "3005"
            - name: KAFKA_CLIENT_ID
              value: "http://payment-service"
            - name: KAFKA_BROKERS
              value: kafka-srv:9092 
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: DOMAIN_BASE_URL
              value: "https://roadmappro.site"    
            # Database Configuration
            - name: DB_HOST
              value: "postgres-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB  
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: FRONT_END_BASE_URL
              value: "client-srv:5173"     
          ports:
            - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
