apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadmap
  template:
    metadata:
      labels:
        app: roadmap
    spec:
      containers:
        - name: roadmap
          image: sahhhall/roadmap
          env:
            - name: PORT
              value: "3001"
            - name: KAFKA_CLIENT_ID
              value: "roadmap-service"
            - name: KAFKA_BROKERS
              value: kafka-srv:9092
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: REDIS_URL
              value: "redis://redis-srv:6379"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-srv
spec:
  selector:
    app: roadmap
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
