apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sahalvavoor313@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
    - http01:
        ingress:
          class: nginx 