apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment
    spec:
      containers:
        - name: assessment
          image: sahhhall/assessment
          env:
            - name: PORT
              value: "3002"
            - name: KAFKA_CLIENT_ID
              value: "assessment-service"
            - name: KAFKA_BROKERS
              value: "kafka-srv:9092"
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-srv
spec:
  selector:
    app: assessment
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000