apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: sahhhall/booking
          env:
            - name: PORT
              value: "3004"
            - name: KAFKA_CLIENT_ID
              value: "booking-service"
            - name: KAFKA_BROKERS
              value: "kafka-srv:9092"
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: FRONT_END_BASE_URL
              value: "client-srv:5173"
            - name: GRPC_PORT
              value: "50051"    
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: booking-srv
spec:
  selector:
    app: booking
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3000