apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: sahhhall/expiration
          env:
            - name: PORT
              value: "3000"
            - name: KAFKA_CLIENT_ID
              value: "expiration-service"
            - name: KAFKA_BROKERS
              value: "kafka-srv:9092"
            - name: KAFKA_CONNECTION_TIMEOUT
              value: "3000"
            - name: GRPC_SERVER
              value: "user-srv:50051"
            - name: REDIS_URL
              value: "redis-srv:6379"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: MONGODB_URI
          ports:
            - containerPort: 3000
