apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadmap
  template:
    metadata:
      labels:
        app: roadmap
    spec:
      containers:
        - name: roadmap
          image: sahhhall/roadmap  
          ports:
            - containerPort: 3000 

---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-srv
spec:
  type: NodePort
  selector:
    app: roadmap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30031 