name: deploy-api-gateway
on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: cd api-gateway && docker build -t sahhhall/api-gateway .
      
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        run: docker push sahhhall/api-gateway
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save Kubernetes config
        run: doctl kubernetes cluster kubeconfig save roadmappro
      
      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment api-gateway-depl
